name: Send Test Email
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawiddr/send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Portfolio Contact"
          body: "You have a new message from your portfolio!"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
